Serien verknüpfen Infotext #395
elan-ev/studip-opencast-plugin pull request #399
Opened 2021-01-21 15:08 UTC by ssrahn

2021-02-04 09:25 UTC, tgloeggl commented
- [ ] Der Text soll sich nur für alle außer Root (Admins / Lehrende / Tutoren) ändern, Root darf weiterhin Serien verknüpfen
- [ ] Die Änderungen an der opencast.po sollen sich auf die relevante Stelle beschränken

2021-02-04 09:25 UTC, tgloeggl requested changes
- [x] Der Text soll sich nur für alle außer Root (Admins / Lehrende / Tutoren) ändern, Root darf weiterhin Serien verknüpfen
- [x] Die Änderungen an der opencast.po sollen sich auf die relevante Stelle beschränken

2021-02-04 10:56 UTC, ssrahn commented
Hab die Änderungen jetzt in die aktuelle .po geschrieben. Root sieht wieder die alte Nachricht

2021-02-11 11:23 UTC, tgloeggl approved these changes

2021-02-11 11:23 UTC, merged