Changes for playlists
elan-ev/studip-opencast-plugin pull request #848
Opened 2023-12-04 09:26 UTC by dennis531

Changes:
- New add playlist dialog in course
    - Shows playlists of work place
- Paging for playlists table
- Filter + Search for playlists
    - Available filters: Tags, Courses, Lecturers

Fixes:
- [Prevent adding the same playlist to course multiple times](https://github.com/elan-ev/studip-opencast-plugin/commit/eec504137f52a175cf54e57bdf2a560a42c9af69)
- [Same tag created by different users is not filterable in videos table](https://github.com/elan-ev/studip-opencast-plugin/commit/09408ef3bf6264051a940529e82c61dc956a4dc5)

Playlists add dialog in course:
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/62642f81-f1e2-43ba-bf18-13cbf081454f)
![image](https://github.com/elan-ev/studip-opencast-plugin/assets/44410838/a84fb3a4-6d2b-47fe-b056-26d63f1e5f08)

2023-12-04 14:43 UTC, tgloeggl requested changes
Erstmal nur rein visuell gechecked, Funktionscheck folgt.

2023-12-04 14:43 UTC, tgloeggl commented on lib/Routes/Course/CourseAddPlaylist.php
> +        if (is_null($playlist_seminar)) {
Hier besser `empty` verwenden

2023-12-04 14:43 UTC, tgloeggl commented on vueapp/components/Playlists/PlaylistAddNewCard.vue
> +                    <!--
Auskommentierter Code kann weg (ich weiß, Copy-Paste, im Original kann der auch weg) ;)

2023-12-04 14:43 UTC, tgloeggl commented on vueapp/components/Playlists/PlaylistsTable.vue
> +                <!--
Ebenfalls weg damit

2023-12-04 15:03 UTC, dennis531 commented
Danke für die Änderungsvorschläge!

2023-12-11 13:56 UTC, tgloeggl approved these changes

2023-12-11 13:56 UTC, merged