Messages for dialogs
elan-ev/studip-opencast-plugin pull request #854
Opened 2023-12-08 08:47 UTC by ssrahn

#833 

- Messages haben neues attribute {dialog: Boolean}
- MessageList hat neues prop {dialog: Boolean}
- Wenn dialog gesetzt, werden in MessageList nur Messages mit dialog attribute angezeigt
- Sobald eine Dialog-MessageList schließt, werden alle Dialog-Messages gelöscht
- So haben Dialoge eigene Messages und Fehlermeldungen, der Hintergrund bleibt damit sauber
- Error die im front end abgefangen werden könnten, sollten jetzt nur noch Messages vom typen 'error' schmeißen
- Die Error-Komponente ist immer noch Global! und fängt momentan nur Fehler von außerhalb ab (hier: [app.js:49](https://github.com/elan-ev/studip-opencast-plugin/blob/5050f0d8f8411897aef455404fe615bb51dacc92/vueapp/app.js#L49))

2023-12-11 14:02 UTC, tgloeggl requested changes

2023-12-11 14:02 UTC, tgloeggl commented on vueapp/components/Videos/VideoUpload.vue
> -        StudipDialog,
Das war wahrscheinlich ein Versehen? :)

2023-12-11 14:36 UTC, ssrahn commented on vueapp/components/Videos/VideoUpload.vue
> -        StudipDialog,
Huch, habs wieder richtig eingerückt

2023-12-14 12:04 UTC, ssrahn commented
Übersetzungen

2023-12-15 09:10 UTC, tgloeggl approved these changes

2023-12-15 09:10 UTC, merged