Display no ghost video rows
elan-ev/studip-opencast-plugin pull request #895
Opened 2024-01-16 16:49 UTC by dennis531

Shows no ghosts videos in table when loading videos. Instead, the video table is hidden when videos are loading and no videos are available.

In the courseware block, the ghost videos are still there.

Close #707

Demo:
https://github.com/elan-ev/studip-opencast-plugin/issues/773

2024-01-18 12:19 UTC, tgloeggl commented
I think this is not the correct solution for the problem in #707

See my comment there: https://github.com/elan-ev/studip-opencast-plugin/issues/707#issuecomment-1898373087

The "ghost" videos (aka loading animation) has to stay, but i should not be triggered when the upload dialog is open.

2024-01-18 12:20 UTC, tgloeggl requested changes
The loading animation should stay and only be hidden if a reload happens while user is in the upload dialog - or even better, no reload of the video list should happen when user uploads a video.

2024-01-26 12:29 UTC, dennis531 commented
It should be fixed now. The animation was always displayed when an axios request was executed.

2024-01-29 10:46 UTC, tgloeggl approved these changes

2024-01-29 10:46 UTC, merged